version: '3.8'

services:
  frontend:
    image: knorz/video-streaming-frontend:latest
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production

  backend:
    image: knorz/video-streaming-backend:latest
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - FLASK_ENV=production

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
