version: '3.8'

services:
  frontend:
    image: knorz/video-streaming-frontend:latest
    expose:
      - "3000"
    environment:
      - NODE_ENV=production

  backend:
    image: knorz/video-streaming-backend:latest
    expose:
      - "5000"
    depends_on:
      - mongo
    environment:
      - FLASK_ENV=production

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

volumes:
  mongo-data:
