name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend
        run: |
          docker build -t knorz/video-streaming-frontend:latest ./frontend
          docker push knorz/video-streaming-frontend:latest

      - name: Build and push backend
        run: |
          docker build -t knorz/video-streaming-backend:latest ./backend
          docker push knorz/video-streaming-backend:latest

      - name: Copy docker-compose.yml to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "./docker-compose.yml"
          target: "/root/video-streaming/"

      - name: Copy nginx.conf to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "./nginx.conf"
          target: "/root/video-streaming/"

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo lsof -t -i tcp:80 -s tcp:listen | xargs --no-run-if-empty sudo kill -9 || true
            sudo lsof -t -i tcp:27017 -s tcp:listen | xargs --no-run-if-empty sudo kill -9 || true
            docker stop $(docker ps -q) || true
            docker rm $(docker ps -a -q) || true
            docker rmi $(docker images -q) || true
            docker volume prune -f || true
            cd /root/video-streaming
            docker-compose down
            docker-compose pull
            docker-compose up -d
